### PR TITLE
commands: add plan sub commands

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
To be reviewed after #17 and #20

This PR adds the `plan` sub commands. First intention was to have a separate `upgrade` and `rollback` commands. There is no need to have separate commands. All we want is to have a *plan*, then it will automatically rollback in case of error.

I'll add `dry-run` and `auto` rollback functionalities once in a later PR.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47972
https://mattermost.atlassian.net/browse/MM-47973

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
btw technically these are breaking changes :P

**Comment by isacikgoz** [comment]
> btw technically these are breaking changes :P

Ah, yeah the command hierarchy has changed now 😅 

That was a very minor part though, but we need to maintain the stability. Re added it.

**Comment by agnivade** [comment]
Sorry going on vacation :) Don't have any more time to review. You'll have to ask someone else :P

**Comment by isacikgoz** [comment]
> Sorry going on vacation :) Don't have any more time to review. You'll have to ask someone else :P

Oh sorry, it starts form tomorrow right? Have fun dude!

**Comment by isacikgoz** [comment]
@noxer you can just take a look into last 3 commits :)

**Comment by isacikgoz** [comment]
@noxer gentle ping :)

**Review by noxer — APPROVED** [review]
Note to self: Don't close tabs before you're done with the review.

**Pull request merged**
