### PR TITLE
Replace the SchemaName with the current schema

### PR DESCRIPTION
**Pull request by agnivade**
In postgres installations, sometimes the table
can be under a different schema. In that case,
we need to be able to access the information_schema.columns
table amongst others and filter by the table_schema.

This PR allows us to replace the {{.SchemaName}}
template in the SQL files with the actual
schema name.

### CODE REVIEW

**Comment by isacikgoz** [comment]
@agnivade I think we can decouple this logic from morph. On the call site we define the `sources.Source` for the morph engine. Which has a very minimal yet powerful method `Migrations() []*models.Migration`. We can actually save pre executed templates in the source.

For example in the mattermost-server we do (this is a pseudo code):
```Go
	src, err := mbindata.WithInstance(&mbindata.AssetSource{
		Names: assetNamesForDriver,
		AssetFunc: func(name string) ([]byte, error) {
			// Adding the new logic here:
			b, err := assets.ReadFile(filepath.Join("migrations", ss.DriverName(), name))
			if err != nil {
				return nil, err
			}
			t := template.Must(template.New("tmp").Parse(string(b)))

			var buf bytes.Buffer
			err = t.Execute(buf, data)
			if err != nil {
				return nil, err
			}

			return buf.Bytes(), nil
		},
	})
	if err != nil {
		return err
	}
```	

WDYT?

**Comment by agnivade** [comment]
Ah yeah, much better. Only one additional config needed for schema name. Let me do that.

Do you want to take care of updating the morph API in server + focalboard, while I make the server changes? Then I won't be blocked updating the morph dependency first.

**Comment by isacikgoz** [comment]
I can do that for sure, but you wouldn't be blocked for needing the new version if we make the changes I proposed :p

**Comment by agnivade** [comment]
Oh that's right :facepalm:

**Pull request closed without merging**
